import 'dart:async';
import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../firebase_options.dart';
import '../models/booking.dart';

/// P2 Firestore sync — same `bookings` collection the web /book form uses.
/// P3: App Check attestation + KYC Storage uploads to /kyc/{uid}/{ref}/.
///
/// Design (offline-first, honest):
/// - Local SharedPreferences cache opens instantly (BookingStore).
/// - Cloud is best-effort: if Firebase isn't configured (no
///   `flutterfire configure` / google-services.json yet) every method
///   degrades to local-only and reports `available == false`.
/// - Guest identity is a Firebase anonymous uid at first launch
///   (no login friction). Falls back to a persisted local UUID offline.
/// - Writes use the web-compatible shape (Booking.toCloudMap) so /admin
///   sees app bookings with zero admin changes.
///
/// P3 ENABLED: KYC uploads go to /kyc/{uid}/{ref}/{id|receipt}.jpg
/// (write own-uid, 5MB image/*; read own + owner allowlist). Enforce
/// App Check + these rules in the Firebase console; the client only attests.
class CloudBookings {  static const _uidKey = 'hdl_anon_uid';
  static const _collection = 'bookings';

  bool _available = false;
  bool get available => _available;

  String? _uid;
  String? get uid => _uid;

  FirebaseFirestore? _db;
  FirebaseAuth? _auth;

  /// Try Firebase init. Returns true when cloud is live, false for
  /// local-only mode. Never throws — P2 must run without Firebase config.
  Future<bool> ensureInitialized() async {
    // Fast path: already live.
    if (_available && _db != null) return true;
    try {
      if (Firebase.apps.isEmpty) {
        // Generated by `flutterfire configure` — real project config, so
        // the app goes cloud-live instead of local-only fallback.
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
      }
      // P3: App Check attestation (best-effort — enforcement is server-side
      // in the Firebase console; debug provider in dev builds only).
      try {
        await FirebaseAppCheck.instance.activate(
          androidProvider:
              kDebugMode ? AndroidProvider.debug : AndroidProvider.playIntegrity,
          appleProvider:
              kDebugMode ? AppleProvider.debug : AppleProvider.appAttest,
        );
      } catch (e) {
        debugPrint('[Cloud] App Check activation deferred: $e');
      }
      _db = FirebaseFirestore.instance;
      _auth = FirebaseAuth.instance;
      // Touch settings to fail fast when misconfigured.
      _db!.settings = const Settings(persistenceEnabled: true);
      _available = true;
    } catch (e) {
      debugPrint('[Cloud] Firebase unavailable, local-only mode: $e');
      _available = false;
    }
    await ensureAnonymousUid();
    return _available;
  }

  /// Anonymous login at first launch (spec §6). Persists uid so reinstalls
  /// keep a stable fallback; Firebase uid wins when online.
  /// Respects an existing session (Google owner/anak): never calls
  /// signInAnonymously over a signed-in user — that would drop the email
  /// token the rules (isAdmin/isAnak) depend on.
  Future<String> ensureAnonymousUid() async {
    if (_uid != null && _uid!.isNotEmpty) return _uid!;
    try {
      final prefs = await SharedPreferences.getInstance();
      final cached = prefs.getString(_uidKey);
      if (_available && _auth != null) {
        final cur = _auth!.currentUser;
        if (cur != null && cur.uid.isNotEmpty) {
          _uid = cur.uid;
          await prefs.setString(_uidKey, cur.uid);
          return cur.uid;
        }
        final cred = await _auth!.signInAnonymously();
        final fbUid = cred.user?.uid;
        if (fbUid != null && fbUid.isNotEmpty) {
          _uid = fbUid;
          await prefs.setString(_uidKey, fbUid);
          return fbUid;
        }
      }
      if (cached != null && cached.isNotEmpty) {
        _uid = cached;
        return cached;
      }
      final local =
          'local-${DateTime.now().millisecondsSinceEpoch}-${Random().nextInt(1 << 32)}';
      await prefs.setString(_uidKey, local);
      _uid = local;
      return local;
    } catch (e) {
      debugPrint('[Cloud] anon uid fallback: $e');
      _uid ??= 'local-fallback-${Random().nextInt(1 << 32)}';
      return _uid!;
    }
  }

  CollectionReference<Map<String, dynamic>>? get _col =>
      _available && _db != null ? _db!.collection(_collection) : null;

  /// Creates bookings/{id} in web shape. Returns doc id, or null offline.
  /// created_at uses serverTimestamp so host ordering + 24h TTL share a clock.
  Future<String?> submitBooking(Booking booking) async {
    final col = _col;
    if (col == null) return null;
    try {
      final payload = booking.toCloudMap()
        ..['created_at'] = FieldValue.serverTimestamp();
      final ref = await col.add(payload);
      return ref.id;
    } catch (e) {
      debugPrint('[Cloud] submit failed (queued locally): $e');
      return null;
    }
  }

  /// Marks KYC submitted on own doc, attaching Storage download URLs.
  /// Status stays pending — host reviews in /admin (approve/reject loop).
  /// Guest allowlist permits kyc_status + kyc_id_url + kyc_receipt_url only
  /// (never kyc_reject_reason — admin-only).
  Future<bool> markKycSubmitted(
    String docId, {
    String? idUrl,
    String? receiptUrl,
  }) async {
    final col = _col;
    if (col == null) return false;
    try {
      final patch = <String, dynamic>{'kyc_status': 'submitted'};
      if (idUrl != null) patch['kyc_id_url'] = idUrl;
      if (receiptUrl != null) patch['kyc_receipt_url'] = receiptUrl;
      await col.doc(docId).update(patch);
      return true;
    } catch (e) {
      debugPrint('[Cloud] markKyc failed: $e');
      return false;
    }
  }

  /// Guest cancels own pending booking.
  Future<bool> cancelOwn(String docId) async {
    final col = _col;
    if (col == null) return false;
    try {
      await col.doc(docId).update({'status': 'Cancelled'});
      return true;
    } catch (e) {
      debugPrint('[Cloud] cancel failed: $e');
      return false;
    }
  }

  /// Saves the one-time ETA Maps link on own doc.
  Future<bool> setEtaShareUrl(String docId, String url) async {
    final col = _col;
    if (col == null) return false;
    try {
      await col.doc(docId).update({'eta_share_url': url});
      return true;
    } catch (e) {
      debugPrint('[Cloud] eta save failed: $e');
      return false;
    }
  }

  /// Owner: saves rider-style pickup (guest one-tap GPS) on any booking doc.
  Future<bool> setPickup(String docId,
      {required double lat, required double lng, String? label}) async {
    final col = _col;
    if (col == null) return false;
    try {
      await col.doc(docId).update({
        'pickup_lat': lat,
        'pickup_lng': lng,
        'pickup_updated_at': DateTime.now().toIso8601String(),
        if (label != null) 'pickup_label': label,
        'eta_share_url':
            'https://www.google.com/maps/search/?api=1&query=$lat,$lng',
      });
      return true;
    } catch (e) {
      debugPrint('[Cloud] pickup save failed: $e');
      return false;
    }
  }

  /// Owner: confirm any booking (host approve path, G2 re-check first).
  Future<bool> confirmBooking(String docId) async {
    final col = _col;
    if (col == null) return false;
    try {
      await col.doc(docId).update({'status': 'Confirmed'});
      return true;
    } catch (e) {
      debugPrint('[Cloud] confirm failed: $e');
      return false;
    }
  }

  /// Owner: cancel any booking.
  Future<bool> cancelBooking(String docId) async {
    final col = _col;
    if (col == null) return false;
    try {
      await col.doc(docId).update({'status': 'Cancelled'});
      return true;
    } catch (e) {
      debugPrint('[Cloud] owner cancel failed: $e');
      return false;
    }
  }

  /// Owner live stream: ALL bookings (not uid-scoped). Used by the owner APK
  /// tabs (Bookings triage + Tracking pickups). Falls back to empty offline.
  Stream<List<Booking>> watchAllBookings({int limit = 100}) {
    final col = _col;
    if (col == null) return const Stream.empty();
    return col
        .orderBy('created_at', descending: true)
        .limit(limit)
        .snapshots()
        .map((snap) =>
            snap.docs.map((d) => Booking.fromCloud(d.id, d.data())).toList())
        .handleError((Object e) {
      debugPrint('[Cloud] watch all failed: $e');
      return <Booking>[];
    });
  }

  /// Query-before-submit overlap check (client-side, best-effort).
  /// Returns conflicting bookings for the same stay whose status is
  /// pending/confirmed/checked_in (either case) and not locally expired.
  /// NOTE(G2): this is racy by nature — the host MUST re-check at approve
  /// time (see stillAvailable + AdminPage Confirm handler). Two simultaneous
  /// submits can both read "free"; last approve wins, loser gets rebook flow.
  Future<List<Booking>> findConflicts({
    required String accommodationId,
    required DateTime checkIn,
    required DateTime checkOut,
    String? excludeRefId,
  }) async {
    final col = _col;
    if (col == null) return [];
    try {
      final snap = await col
          .where('accommodation', isEqualTo: accommodationId)
          .limit(50)
          .get();
      final out = <Booking>[];
      for (final d in snap.docs) {
        final b = Booking.fromCloud(d.id, d.data());
        if (excludeRefId != null && b.referenceId == excludeRefId) continue;
        if (b.blocksRange(checkIn, checkOut, sameStay: accommodationId)) {
          out.add(b);
        }
      }
      return out;
    } catch (e) {
      // Missing composite index or offline → fail open, local check still runs.
      debugPrint('[Cloud] conflict query fallback to local: $e');
      return [];
    }
  }

  /// Host-side re-check helper (call at approve time, G2).
  /// Returns true when no other active booking blocks the range.
  Future<bool> stillAvailable({
    required String accommodationId,
    required DateTime checkIn,
    required DateTime checkOut,
    String? excludeRefId,
  }) async {
    final conflicts = await findConflicts(
      accommodationId: accommodationId,
      checkIn: checkIn,
      checkOut: checkOut,
      excludeRefId: excludeRefId,
    );
    return conflicts.isEmpty;
  }

  /// Live stream of the guest's own bookings (uid-scoped, §6).
  /// Emits empty on error so the dashboard falls back to local cache.
  Stream<List<Booking>> watchOwnBookings(String uid) {
    final col = _col;
    if (col == null) return const Stream.empty();
    return col
        .where('uid', isEqualTo: uid)
        .orderBy('created_at', descending: true)
        .snapshots()
        .map((snap) =>
            snap.docs.map((d) => Booking.fromCloud(d.id, d.data())).toList())
        .handleError((Object e) {
      debugPrint('[Cloud] watch own failed, using local: $e');
      return <Booking>[];
    });
  }
}
