// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLiLB2JFcyKMkrCkrjY30-oZ2XJ6qP_E0',
    appId: '1:648433185:android:edcc607c8ea7a1af811d60',
    messagingSenderId: '648433185',
    projectId: 'hacienda-de-luisana',
    storageBucket: 'hacienda-de-luisana.firebasestorage.app',

    // LIVE LOCATION IS OFF until this is filled in, and that is deliberate
    // rather than an oversight — see ADR-0013.
    //
    // The Admin's live-location panel reads the ephemeral position stream out of
    // the Realtime Database, and `LiveLocationService.hasTransport` is false
    // without a `databaseURL`, so the panel says "this build has no live-location
    // channel configured" instead of half-working.
    //
    // Two things are needed, in this order, and neither is guessable from here:
    //
    //   1. The Realtime Database has to EXIST in the live project. Create it in
    //      the Firebase console (Build -> Realtime Database). Until it does,
    //      there is no URL to copy and a filled-in value would just fail at
    //      runtime looking configured.
    //   2. Its URL, of the form
    //          https://<projectId>-default-rtdb.<region>.firebasedatabase.app
    //      which for this project is
    //          https://hacienda-de-luisana-default-rtdb.<region>.firebasedatabase.app
    //      The `<region>` is whichever region the console created it in, so it is
    //      copied from the console rather than derived. Left empty here on
    //      purpose: a guessed region is a runtime network error dressed up as a
    //      configured build.
    //
    // The same value goes in the other platform block below, and in
    // `VITE_FIREBASE_DATABASE_URL` for the website (see `.env.example`), which is
    // the Guest half of the same feature.
    databaseURL: '',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcz2xTehQ1CY5MyUMdw87RviknNHd5kCA',
    appId: '1:648433185:ios:20b6b31ff6c9885f811d60',
    messagingSenderId: '648433185',
    projectId: 'hacienda-de-luisana',
    storageBucket: 'hacienda-de-luisana.firebasestorage.app',
    iosBundleId: 'com.haciendadeluisana.app',

    // The same value as the Android block, and for the same reasons. See the note
    // there: the Realtime Database has to exist first, and `<region>` is copied
    // from the console.
    databaseURL: '',
  );
}
