// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLiLB2JFcyKMkrCkrjY30-oZ2XJ6qP_E0',
    appId: '1:648433185:android:edcc607c8ea7a1af811d60',
    messagingSenderId: '648433185',
    projectId: 'hacienda-de-luisana',
    storageBucket: 'hacienda-de-luisana.firebasestorage.app',

    // The ephemeral live-location stream (ADR-0013). The Admin's panel reads
    // positions out of the Realtime Database, and `LiveLocationService.hasTransport`
    // is false without this — before it was set, the panel said "this build has no
    // live-location channel configured" instead of half-working.
    //
    // `us-central1` confirmed against the live instance rather than guessed: an
    // unauthenticated read of the root returns 401 ("Permission denied"), which is
    // what `".read": false` should produce, while the same request at another
    // region returns 404 ("no such instance"). Keep it in step with
    // `VITE_FIREBASE_DATABASE_URL` in `.env.local`, which is the Guest half.
    databaseURL: 'https://hacienda-de-luisana-default-rtdb.us-central1.firebasedatabase.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcz2xTehQ1CY5MyUMdw87RviknNHd5kCA',
    appId: '1:648433185:ios:20b6b31ff6c9885f811d60',
    messagingSenderId: '648433185',
    projectId: 'hacienda-de-luisana',
    storageBucket: 'hacienda-de-luisana.firebasestorage.app',
    iosBundleId: 'com.haciendadeluisana.app',

    // The same value as the Android block, and for the same reason. See the note
    // there for how the region was confirmed.
    databaseURL: 'https://hacienda-de-luisana-default-rtdb.us-central1.firebasedatabase.app',
  );
}
